name: Trigger auto deployment for deptest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/deptest-AutoDeployTrigger-0243dcae-a706-4036-9531-dd5aa72ff33b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.DEPTEST_REGISTRY_USERNAME }}
          password: ${{ secrets.DEPTEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.hub.docker.com/astha0710/deptest:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEPTEST_AZURE_CREDENTIALS }}

      - uses: actions/checkout@v3
      - name: Decrypt large secret
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
      - name: Test printing your secret (Remove this step in production)
        run: cat secrets.AZURE_CREDENTIALS 
        
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az 
            az containerapp registry set -n deptest -g rg --server registry.hub.docker.com --username  astha0710 --password 0710astha
            az containerapp update -n deptest -g rg --image registry.hub.docker.com/astha0710/deptest:${{ github.sha }}
