name: Trigger auto deployment for deptest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/deptest-AutoDeployTrigger-a3f06324-812c-4062-b491-bcc594b4c37a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DEPTEST_REGISTRY_USERNAME }}
          password: ${{ secrets.DEPTEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: astha0710/deptest:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEPTEST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            docker logout
            az containerapp registry set -n deptest -g rg --server docker.io --username  ${{ secrets.DEPTEST_REGISTRY_USERNAME }} --password ${{ secrets.DEPTEST_REGISTRY_PASSWORD }}
            az containerapp update -n deptest -g rg --image astha0710/deptest:${{ github.sha }}
