name: Trigger auto deployment for deptest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/deptest-AutoDeployTrigger-0243dcae-a706-4036-9531-dd5aa72ff33b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEPTEST_AZURE_CREDENTIALS }}
        
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            echo DEPTEST_AZURE_CREDENTIALS

