name: Trigger auto deployment for deptestastha

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/deptestastha-AutoDeployTrigger-dc8192b9-b339-4eac-ac2a-27edf6cdb546.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.DEPTESTASTHA_REGISTRY_USERNAME }}
          password: ${{ secrets.DEPTESTASTHA_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.hub.docker.com/deptest:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEPTESTASTHA_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n deptestastha -g rg --server registry.hub.docker.com --username  ${{ secrets.DEPTESTASTHA_REGISTRY_USERNAME }} --password ${{ secrets.DEPTESTASTHA_REGISTRY_PASSWORD }}
            az containerapp update -n deptestastha -g rg --image registry.hub.docker.com/deptest:${{ github.sha }}
